#!/sh


if [[ -z "$1" ]]; then
    echo "Project name not specified"
    return
fi

project_name=$1

mkdir src/${project_name}
cp -Rf src/template src/${project_name}
cd src/${project_name}



# find ./ -type f -exec sed -i $('s/<template>/${project_name}/g') {} \;

echo "Project created 🚀"
